Add authorizations for iscn and likenft
likecoin/likecoin-chain pull request #92
Opened 2022-12-13 05:09 UTC by nnkken

- [ ] granting update permission on iscn id, without transfer ownership
- [ ] granting modify permission on nft royalty config
- [ ] granting update listing permission on nft marketplace
- [ ] granting update offer permission on nft marketplace
- [ ] granting update permission on nft class id
- [ ] granting mint permission on nft class id
- [ ] test cases for iscn authorizations
- [ ] test cases for likenft authorizations

2022-12-30 16:25 UTC, williamchong requested changes
Want to add support for more message after reviewing, sorry for the trouble

2022-12-30 16:25 UTC, williamchong commented on x/likenft/types/authz.go
> +}
Please also support NewClass via ISCN ID

2023-01-03 01:48 UTC, nnkken commented on x/likenft/types/authz.go
> +	return sdk.MsgTypeURL(&MsgMintNFT{})
Class owner.
In authz, the authz module only validates the `MsgExec` wrapper, then the wrapped message is forwarded to the corresponding message handler, like normal message execution.
The `MsgMintNFT` message specifies who receives the NFT (by the `creator` field), so it's nothing related to the authz caller.

2023-01-03 01:50 UTC, nnkken commented on x/likenft/types/authz.go
> +	return sdk.MsgTypeURL(&MsgUpdateRoyaltyConfig{})
Yes it throws

2023-01-03 01:53 UTC, nnkken commented on x/likenft/types/authz.go
> +	}
OK.
Do you think `empty NftId = allow all NFT IDs` is a good design?

2023-01-03 03:46 UTC, williamchong commented on x/likenft/types/authz.go
> +	}
Yes it would work

2023-01-03 03:46 UTC, williamchong commented on x/likenft/types/authz.go
> +	return sdk.MsgTypeURL(&MsgMintNFT{})
We would need authz for MsgSend NFT too to use as combo for this to be useful then

2023-01-19 20:29 UTC, williamchong approved these changes

2023-01-19 20:29 UTC, merged